version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/nginx/:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: config/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./data:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log

  mysql:
    image: postgres:15
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cms_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - internal

networks:
  internal:
    driver: bridge